# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.TextField(max_length=50, verbose_name=b'Descricao'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departament', verbose_name=b'Departamento'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(max_length=100, verbose_name=b'E-mail'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.TextField(max_length=100, verbose_name=b'Nome'),
        ),
    ]
