# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
